services:
  - type: web
    name: rag-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn trpc_backend:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: OPENAI_API_KEY
        sync: false
      - key: API_KEY
        generateValue: true
      - key: RATE_LIMIT_PER_MINUTE
        value: 60
    healthCheckPath: /trpc/health
    autoDeploy: true
    disk:
      name: sqlite-data
      mountPath: /data
      sizeGB: 1
